export enum ORDERSTATUS {
    IN_UNIT, COMPLETED, DELIVERED, CANCELLED
}

export enum PAYMENTSTATUS {
    NOT_DELIVERED, NOT_PAID, PARTIALLY_PAID, PAID
}

export enum PAYMENTTYPE{
    CASH,UPI,NOT_PAY
}

